services:
  grug-static:
    container_name: grug-static
    environment:
      PORT: 4567
    ports:
      - "4567:4567"
    working_dir: /app
    volumes:
      - ./assets:/app/assets
      - ./index.html:/app/index.html
      - ./static-server.js:/app/static-server.js
    build:
      dockerfile: Dockerfile
    command: nodemon ./static-server.js

  grug-api:
    container_name: grug-api
    ports:
      - "5595:5595"
    working_dir: /app
    volumes:
      - ./api-server.js:/app/api-server.js
    command: nodemon ./api-server.js
    build:
      dockerfile: Dockerfile
    env_file: env

  grug-postgres:
    # docker exec -it grug-postgres psql -U postgres -d grug
    container_name: grug-postgres
    image: postgres:17
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: env
